name: Build and Push API Image

on:
  push:
    branches: [main]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image (latest)
        run: |
          docker build -t bqmxnh/ids-cloud-api:latest ./api

      - name: Push Docker image (latest)
        run: |
          docker push bqmxnh/ids-cloud-api:latest
