name: Build and Push API Image

on:
  push:
    paths:
      - "api/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" |
           docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push image with SHA
      run: |
        IMAGE_TAG=${{ github.sha }}
        docker build -t bqmxnh/ids-cloud-api:$IMAGE_TAG ./api
        docker push bqmxnh/ids-cloud-api:$IMAGE_TAG

        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Update Helm chart values.yaml
      run: |
        sed -i "s/^  tag:.*/  tag: \"${IMAGE_TAG}\"/" charts/ids-api/values.yaml

    - name: Commit updated Helm chart
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add charts/ids-api/values.yaml
        git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
        git push
