name: Build, Push and Deploy IDS API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "charts/ids-api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Image
      run: |
        TAG=${{ github.sha }}
        docker build -t bqmxnh/ids-cloud-api:$TAG ./api
        docker push bqmxnh/ids-cloud-api:$TAG

    - name: Update Helm Chart with new image tag
      run: |
        TAG=${{ github.sha }}
        sed -i "s|tag:.*|tag: \"$TAG\"|" charts/ids-api/values.yaml

    - name: Commit changes to Helm chart
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add charts/ids-api/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push || echo "No changes to push"
