name: Build and Push API Image

on:
  push:
    paths:
      - "api/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Docker Image
      run: |
        IMAGE_SHA=${{ github.sha }}

        echo "Building image with SHA: $IMAGE_SHA"

        # Build image with SHA tag
        docker build -t bqmxnh/ids-cloud-api:$IMAGE_SHA ./api

        # Push SHA tag
        docker push bqmxnh/ids-cloud-api:$IMAGE_SHA

        # Tag latest
        docker tag bqmxnh/ids-cloud-api:$IMAGE_SHA bqmxnh/ids-cloud-api:latest

        # Push latest
        docker push bqmxnh/ids-cloud-api:latest

        echo "Pushed latest and SHA image successfully!"
